### ISSUE TITLE
Uncaught Error: Cannot find module 'undefined' in _prelude.js

### ISSUE THREAD

**Issue by damienadermann** [browserify-rails/browserify-rails#82] opened 2015-05-29 00:55 UTC
Hi I've been trying to solve a bug and am going nowhere.

I'm using browserify-rails and babelify. I have an npm dependency written in es6(babel) and it uses react. 

Locally everything runs perfectly but when I deploy to our edge environment I'm getting

```
Uncaught Error: Cannot find module 'undefined'
  s @ _prelude.js:1
  (anonymous function) @ shouldUpdateReactComponent.js:12
```
To deploy I'm using capistrano with capistrano-npm

The sourcemap doesn't seem to show the correct line in shouldUpdateReactComponent because line 12 is before the 'use-strict' in that file.

My application.rb includes
```
 30     config.browserify_rails.source_map_environments += ["development"]
 31     config.browserify_rails.commandline_options = '-t babelify --extension=.jsx'
```

The sprockets created application.js looks correct however it does include sourcemaps even when I remove edge from the source maps list.

**Comment by cymen** [comment] 2015-05-29 01:12
Most basic thing to check first is to make sure you have all of the npm dependencies in the right group -- is anything in the dev group that really should be in the regular dependency group that might prevent build? Simple way to check is just move everything from devDependencies to dependencies just to be 100% sure.

I'm thinking some more but hopefully others can chime in too if they have hit this.

You should be able to reproduce it locally by doing:

`RAILS_ENV=production bundle exec rake assets:precompile`

So you could try that first to see if it fails on local too. If not, blow away `node_modules` and run `npm install --production` or `NODE_ENV=production npm install` and then try to generate the assets again -- if it fails, it is something that is in devDependencies that should be in dependencies.

**Comment by damienadermann** [comment] 2015-05-29 01:27
Hi @cymen, I really appreciate you looking into this.

All my dependences are in "dependencies" so thats not an issue. Running assets:precompile in both production and edge envs didn't replicate the issue. Neither did npm install --production.

One thing I didn't mention is I'm running locally with osx and webrick and on edge with puma/ubuntu.

**Comment by cymen** [comment] 2015-11-23 10:55
Closing as unable to replicate (not sure how to). Please reopen if this is still of interested (but please try browserify-rails 2.x to see if the issue is resolved first).

**Closed by cymen** 2015-11-23 10:55 UTC
