### ISSUE TITLE
Heroku: Push rejected, failed to compile Multipack app

### ISSUE THREAD

**Issue by rreusser** [browserify-rails/browserify-rails#94] opened 2015-07-01 19:52 UTC
I followed the `heroku-buildpack-multi` instructions in the README and now just receive a cursory 'Push rejected' message. I [commented on a heroku-buildpack-multi issue](https://github.com/ddollar/heroku-buildpack-multi/issues/24) since the output appears rather unhelpful.

I understand this is likely not actually a browserify-rails issue, but it's not clear to me exactly where I've gone wrong, so I imagine other people may run into the same issue. A quick google search indicates that a Gemfile and package.json with correct fields are relevant, but beyond that I don't have too much to go on here. Suggestions greatly appreciated!

```
.buildpacks:
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

```json
package.json:
{
  "name": "app-name",
  "version": "0.1.0",
  "dependencies": {
    "browserify": "~> 10.2.4",
    "browserify-incremental": "^3.0.1"
  },
  "license": "MIT",
  "engines": {
    "node": ">= 0.10"
  },
  "private": true
}
```

```
$ git push heroku stage:master
Counting objects: 75, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (70/70), done.
Writing objects: 100% (75/75), 9.86 KiB | 0 bytes/s, done.
Total 75 (delta 45), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Removing .DS_Store files
remote: -----> Fetching custom git buildpack... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: .buildpacks
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to app-name.
remote: 
To https://git.heroku.com/app-name.git
 ! [remote rejected] stage -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/app-name.git'
```

**Comment by cymen** [comment] 2015-07-01 19:56
I'm trying to think what it might be. Does your Gemfile have `browserify-rails` available in production environment? The build will run in production environment so it has to be enabled there but it only runs to build the assets -- won't be run on every request like it would in develoment.

**Comment by rreusser** [comment] 2015-07-01 19:58
@cymen Thanks for the prompt reply! @uhoh-itsmaciek suggests that heroku supports buildpacks natively so that

```
$ heroku buildpacks:set https://github.com/ddollar/heroku-buildpack-multi.git
```

might be the right answer and require just a quick README update. Waiting to test…

```
 !    You do not have permission to manage app on beacon-stage. Only the app owner, <collaborator-in-a-meeting-right-now>, can do that.
```

**Comment by cymen** [comment] 2015-07-01 19:59
Oh right, that is an important step.

**Comment by cymen** [comment] 2015-07-01 20:01
By the way, if you do find the documentation should be updated PRs are welcome! If you don't have time, you can comment here and I'll try to get it in.

**Comment by uhoh-itsmaciek** [comment] 2015-07-01 20:01
@rreusser supports *multiple* buildpacks natively. So you shouldn't need multibuildpack at all: you should be able to just `heroku buildpacks:add` the necessary buildpacks.

**Comment by uhoh-itsmaciek** [comment] 2015-07-01 20:02
Here's the DevCenter link: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by rreusser** [comment] 2015-07-01 20:04
Good catch, @uhoh-itsmaciek! Thanks. Still modifying buildpacks via slack chat with app owner. Will submit PR when solution is determined.

**Comment by cymen** [comment] 2015-07-09 19:51
Closing as this appears to be resolved. Please reopen if I'm wrong/missing something.

**Comment by rreusser** [comment] 2015-07-09 19:52
Perfect, nope, All good. Just my ignorance. Thanks again.

**Closed by cymen** 2015-07-09 19:51 UTC

**Comment by mykolas921** [comment] 2017-10-28 09:01
@rreusser what was the issue?
I'm facing the same issue.

remote: -----> Deleting 14 files matching .slugignore patterns.
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz

**Comment by cymen** [comment] 2017-10-28 23:34
@mykolas921 are you following https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app ?

**Comment by mykolas921** [comment] 2017-10-29 02:01
@cymen Solved the issue. The problem is in .slugignore file. "*.json" is in the file.
